# Site settings

# Title of the Webpage (e.g. group name)
title: "VCP Stamm Ernsbach Limestor Sindringen"
# Short description of the group (single line)
description: "Pfadfinden unter dem Limestor."
# Name of the group
group_name: VCP Stamm Ernsbach Limestor Sindringen
# Address of the group
group_address: >
  Kirchweg 3<br/>
  74670 Ernsbach
# Phone number of the group
group_phone: 
# Emailadress of the group
group_email: 
# Name of the Webmaster
name: 'Andreas Zipf'
# Emailadress of the Webmaster
email: 

# URL of the webpage
url: "http://vcp-ELS.github.io/" # the base hostname & protocol for your site

# Images

#blog logo
logo: "/assets/images/VCP-Zeichen-RGB-128px.png"
# blog cover
cover: "/assets/images/VCP_Plakate_2012_3_lowres.jpg"

# Build settings
markdown: redcarpet
highlighter: pygments

collections:
  team:

  groups:
    output: true

baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/VCP_de
    desc: Folge mir auf twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/groups/vcp.oearbeit/?fref=ts
    desc: Folge mir auf facebook
    share_url: //www.facebook.com/sharer/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
