# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "VCP Stamm Martin Luther"
description: > # this means to ignore newlines until "email:"
   Pfadfinden in Eisenach.

email: info@johannes-engelke.de
#blog logo
logo: "/assets/images/VCP-Zeichen-RGB-128px.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Walter Webmaster'

group_name: VCP Stamm Martin Luther
group_address: >
  Am Kirchweg 3<br/>
  12345 Eisenach

group_phone: 0123 / 456 78 90
group_email: kontakt@test-stamm.de


collections:
  team:

  groups:
    output: true

url: "http://joek.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/VCP_de
    desc: Folge mir auf twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/groups/vcp.oearbeit/?fref=ts
    desc: Folge mir auf facebook
    share_url: //www.facebook.com/sharer/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
